### ISSUE TITLE
java.lang.NoSuchMethodError com/voxeet/android/media/MediaSDK

### ISSUE THREAD

**Issue by krishnamanieee** [voxeet/android-sdk-sample#2]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.voxeet.sdk.sample, PID: 7632
    java.lang.NoSuchMethodError: No virtual method getPeerVuMeter(Ljava/lang/String;)D in class Lcom/voxeet/android/media/MediaSDK; or its super classes (declaration of 'com.voxeet.android.media.MediaSDK' appears in /data/app/fr.voxeet.sdk.sample-2/base.apk)
        at voxeet.com.sdk.core.abs.AbstractConferenceSdkService.currentSpeaker(AbstractConferenceSdkService.java:519)
        at com.voxeet.toolkit.implementation.VoxeetCurrentSpeakerView$1.run(VoxeetCurrentSpeakerView.java:62)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by codlab** [comment]
This issue is resolved in the `1.1.8.27`
